--INIT USER
INSERT INTO USER(USERNAME, PASSWORD, ACCOUNT_NON_EXPIRED, ACCOUNT_NON_LOCKED, CREDENTIALS_NON_EXPIRED, ENABLED, AUTHORITIES) VALUES('admin','$2a$10$i2Ayn28fzaWsFCWpSp9Av.qhwGTBQjGxN83uERxodVPSdtDiooUYa', true, true, true, true, 'USER,ADMIN');
INSERT INTO USER(USERNAME, PASSWORD, ACCOUNT_NON_EXPIRED, ACCOUNT_NON_LOCKED, CREDENTIALS_NON_EXPIRED, ENABLED, AUTHORITIES) VALUES('user','$2a$10$.PF.37H3XjBUqBTYRUFxBOcgKk90NKNplXDnearbv6GKmSl/85m8W', true, true, true, true, 'USER');

--INIT AUTHOR
INSERT INTO AUTHOR(AUTHOR_NAME, CREATE_BY_ID, CREATE_DATE) VALUES('Adam', 2, '2018-09-16 12:00:00');

--INIT BOOK
INSERT INTO BOOK(BOOK_NAME, CREATE_BY_ID, CREATE_DATE) VALUES('English level B2', 2, '2018-09-16 12:00:00');

